const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },{
        src: './images/kurly_003.jpg',
        name: '[오뚜기] 진짬뽕 컵라면 6입',
        summary: '얼큰하고 진한 국물의 매력',
        price:4980,
        sale:15,
        review:84,
    },
    {
        src: './images/kurly_004.jpg',
        name: '[청정원] 클래식 불고기 양념 500g',
        summary: '달콤짭짤한 불고기 맛의 기본',
        price:3200,
        sale:10,
        review:47,
    },
    {
        src: './images/kurly_005.jpg',
        name: '[빙그레] 바나나맛 우유 6개입',
        summary: '언제 먹어도 맛있는 국민 간식',
        price:4980,
        sale:5,
        review:120,
    },
    {
        src: './images/kurly_006.jpg',
        name: '[서울우유] 초코 멸균우유 200ml x 6팩',
        summary: '진한 초코 맛으로 달콤하게',
        price:4350,
        sale:12,
        review:39,
    },
    {
        src: './images/kurly_007.jpg',
        name: '[풀무원] 탱탱쫄면 4인분',
        summary: '탱글탱글 면발에 매콤한 양념',
        price:5780,
        sale:8,
        review:62,
    },
    {
        src: './images/kurly_008.jpg',
        name: '[삼양] 불닭볶음면 5입',
        summary: '매운 맛 마니아들의 선택',
        price:4350,
        sale:10,
        review:213,
    },
    {
        src: './images/kurly_009.jpg',
        name: '[농심] 새우깡 오리지널 90g x 3봉',
        summary: '바삭하고 고소한 새우맛 스낵',
        price:2850,
        sale:6,
        review:98,
    },
    {
        src: './images/kurly_010.jpg',
        name: '[롯데] 칸쵸 54g x 3개',
        summary: '초코가 톡톡, 귀여운 과자',
        price:2500,
        sale:5,
        review:67,
    },
    {
        src: './images/kurly_011.jpg',
        name: '[CJ] 햇반 210g x 12개입',
        summary: '간편하게 즐기는 따뜻한 밥',
        price:11800,
        sale:18,
        review:330,
    },
    {
        src: './images/kurly_012.jpg',
        name: '[동원] 리챔 클래식 200g x 3개입',
        summary: '짭조름한 햄으로 반찬 끝!',
        price:8980,
        sale:10,
        review:142,
    },    
]